services:
  shake-detect-service:
    image: shake-detect-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181" # WS
      - "8182:8182" # Metrics
    restart: always
    volumes:
      - ./data:/app/data:rw
