services:
  shake-detect-service:
    image: shake-detect-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./data:/app/data:rw
